
export const CMSType = {

    REQUEST_SUB_CATEGORY: "REQUEST_SUB_CATEGORY",
    REQUEST_ADD_SUB_CATE: "REQUEST_ADD_SUB_CATE",
    REQUEST_EDIT_SUB_CATE: "REQUEST_EDIT_SUB_CATE",
    REQUEST_DELETE_SUB_CATE: "REQUEST_DELETE_SUB_CATE",
    
}