export const REQUEST_HAS_ERRORED = "REQUEST_HAS_ERRORED";

export const REQUEST_IS_LOADING = "REQUEST_IS_LOADING";

export const UNKNOWN_ACTION = "UNKNOWN_ACTION";

export const REQUECT_HOME_DATA = "REQUECT_HOME_DATA";

export const REQUEST_FETCH_SUCCESS = "REQUEST_FETCH_SUCCESS";

export const REQUEST_UPDATE_SUCCESS = "REQUEST_UPDATE_SUCCESS";

export const REQUEST_DELETE_SUCCESS = "REQUEST_DELETE_SUCCESS";

export const REQUEST_CREATE_SUCCESS = "REQUEST_CREATE_SUCCESS";
