
export const FETCH_GIS = "FETCH_GIS";

export const FETCH_DISTRICTS = "FETCH_DISTRICTS";

export const FETCH_DISTRICT = "FETCH_DISTRICT";

export const FETCH_DISTRICT_COORDINATES = "FETCH_DISTRICT_COORDINATES";

export const FETCH_REGIONS = "FETCH_REGIONS";

export const FETCH_REGION = "FETCH_REGION";

export const FETCH_MAREP_CENTERS = "FETCH_MAREP_CENTERS";

export const FETCH_POLYGON_CENTROID = "FETCH_POLYGON_CENTROID";

export const FETCH_DISTRICT_MAREP_CENTERS = "FETCH_DISTRICT_MAREP_CENTERS";

export const FETCH_REGION_MAREP_CENTERS = "FETCH_REGION_MAREP_CENTERS";
