
export const GisType = {
    FETCH_GIS: "FETCH_GIS",
    FETCH_DISTRICTS: "FETCH_DISTRICTS",
    FETCH_DISTRICT: "FETCH_DISTRICT",
    FETCH_DISTRICT_COORDINATES: "FETCH_DISTRICT_COORDINATES",
    FETCH_REGIONS: "FETCH_REGIONS",
    FETCH_REGION: "FETCH_REGION",
    FETCH_MAREP_CENTERS: "FETCH_MAREP_CENTERS",
    FETCH_POLYGON_CENTROID: "FETCH_POLYGON_CENTROID",
    FETCH_DISTRICT_MAREP_CENTERS: "FETCH_DISTRICT_MAREP_CENTERS",
    FETCH_REGION_MAREP_CENTERS:"FETCH_REGION_MAREP_CENTERS",
}
