
export const NewsType = {
    REQUEST_ALL_ARTICLES: 'REQUEST_ALL_ARTICLES',
    REQUEST_SINGLE_ARTICLE: 'REQUEST_SINGLE_ARTICLE',
    REQUEST_EDIT_ARTICLE: 'REQUEST_EDIT_ARTICLE',
    REQUEST_CREATE_ARTICLE: 'REQUEST_CREATE_ARTICLE',
}
