
export const UserType = {
    REQUEST_USER_LOGOUT: "REQUEST_USER_LOGOUT",
    REQUEST_USER_LOGIN: "REQUEST_USER_LOGIN",
    REQUEST_USER_REGISTER: 'REQUEST_USER_REGISTER',

    REQUEST_USER_CONTACT_US: 'REQUEST_USER_CONTACT_US',
    REQUEST_USER_CONTACT: 'REQUEST_USER_CONTACT',
}
